services:
  mysql:
    image: mysql:8.0
    container_name: store-mysql
    restart: always
    environment:
      MYSQL_DATABASE: store_db
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: adham
      MYSQL_PASSWORD: adham123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: