spring.application.name=store-management-system
spring.datasource.url=${DB_URL}
spring.datasource.username=adham
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

logging.level.root=INFO
logging.level.com.adham.store_management_system=DEBUG
logging.level.org.springframework.security=DEBUG

logging.file.name=logs/store-management-system.log
logging.file.max-size=10MB
logging.file.max-history=30
logging.file.total-size-cap=500MB

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
